// frontend/src/views/DeviceModelsView.vue
<template>
  <el-card>
    <template #header>
      <div class="row">
        <span>设备型号</span>
        <el-button v-if="canWrite" type="primary" @click="openAdd">添加设备型号</el-button>
      </div>
    </template>

    <el-table :data="items" border stripe row-key="_id">
      <el-table-column label="序号" width="72" align="center">
        <template #default="{ $index }">{{ revIdx($index) }}</template>
      </el-table-column>
      <el-table-column prop="_id" label="设备型号ID" width="200" show-overflow-tooltip />
      <el-table-column prop="name" label="设备型号名称" min-width="140" />
      <el-table-column prop="description" label="设备型号描述" min-width="160" show-overflow-tooltip />
      <el-table-column prop="status" label="设备型号状态" width="110" />
      <el-table-column label="创建时间" width="170">
        <template #default="{ row }">{{ formatDateTime(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="更新时间" width="170">
        <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
      </el-table-column>
      <el-table-column prop="created_by" label="创建人" width="100" show-overflow-tooltip />
      <el-table-column prop="updated_by" label="更新人" width="100" show-overflow-tooltip />
      <el-table-column v-if="canWrite" label="操作" width="140" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openEdit(row)">编辑</el-button>
          <el-button link type="danger" @click="remove(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      class="table-pager"
    />

    <el-dialog v-model="formDlg" :title="formDlgTitle" width="520px">
      <el-form :model="form" label-width="120px">
        <el-form-item label="设备型号名称" required>
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="设备型号描述">
          <el-input v-model="form.description" type="textarea" :rows="3" />
        </el-form-item>
        <el-form-item label="设备型号状态" required>
          <el-select v-model="form.status" style="width: 100%">
            <el-option v-for="s in DEVICE_MODEL_STATUS" :key="s" :label="s" :value="s" />
          </el-select>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="formDlg = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveForm">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import http from "@/api/http";
import { ElMessage, ElMessageBox } from "element-plus";
import { DEVICE_MODEL_STATUS } from "@/constants/options";
import { canWriteDeviceModel } from "@/stores/auth";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

const items = ref<Record<string, unknown>[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = ref(DEFAULT_PAGE_SIZE);
const skip = computed(() => skipForPage(page.value, pageSize.value));

function revIdx($index: number) {
  return reverseSerialIndex(total.value, skip.value, $index);
}
const canWrite = computed(() => canWriteDeviceModel());

const formDlg = ref(false);
const formMode = ref<"add" | "edit">("add");
const editingId = ref<string | null>(null);
const saving = ref(false);

const form = reactive({
  name: "",
  description: "",
  status: DEVICE_MODEL_STATUS[0],
});

const formDlgTitle = computed(() => (formMode.value === "add" ? "添加设备型号" : "修改设备型号"));

async function load() {
  const { data } = await http.get("/api/device-models", {
    params: { skip: skip.value, limit: pageSize.value },
  });
  const list = (data.items || []) as Record<string, unknown>[];
  const t = Number((data as { total?: number }).total);
  if (list.length === 0 && t > 0 && page.value > 1) {
    page.value = 1;
    return load();
  }
  items.value = list;
  total.value = Number.isFinite(t) ? t : 0;
}

function openAdd() {
  formMode.value = "add";
  editingId.value = null;
  Object.assign(form, {
    name: "",
    description: "",
    status: DEVICE_MODEL_STATUS[0],
  });
  formDlg.value = true;
}

function openEdit(row: Record<string, unknown>) {
  formMode.value = "edit";
  editingId.value = String(row._id);
  form.name = String(row.name || "");
  form.description = String(row.description || "");
  form.status = String(row.status || DEVICE_MODEL_STATUS[0]);
  formDlg.value = true;
}

async function saveForm() {
  saving.value = true;
  try {
    if (formMode.value === "add") {
      await http.post("/api/device-models", {
        name: form.name,
        description: form.description,
        status: form.status,
      });
    } else if (editingId.value) {
      await http.put(`/api/device-models/${editingId.value}`, {
        name: form.name,
        description: form.description,
        status: form.status,
      });
    }
    formDlg.value = false;
    ElMessage.success("已保存");
    await load();
  } finally {
    saving.value = false;
  }
}

async function remove(row: Record<string, unknown>) {
  await ElMessageBox.confirm(`确定删除设备型号「${row.name}」？`, "删除", { type: "warning" });
  await http.delete(`/api/device-models/${row._id}`);
  ElMessage.success("已删除");
  await load();
}

watch(pageSize, () => {
  page.value = 1;
});
watch(
  [page, pageSize],
  () => {
    void load();
  },
  { immediate: true }
);
</script>

<style scoped>
.row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// frontend/src/views/DeviceModelsView.tsx
import { useEffect, useMemo, useState } from "react";
import { Table, Button, Modal, Form, Input, Select, message, Card } from "antd";
import type { TablePaginationConfig } from "antd";
import http from "@/api/http";
import { DEVICE_MODEL_STATUS } from "@/constants/options";
import { canWriteDeviceModel } from "@/stores/auth";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type Row = Record<string, unknown>;

export default function DeviceModelsView() {
  const [items, setItems] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [dlg, setDlg] = useState(false);
  const [mode, setMode] = useState<"add" | "edit">("add");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form] = Form.useForm();
  const canWrite = canWriteDeviceModel();
  const skip = useMemo(() => skipForPage(page, pageSize), [page, pageSize]);

  async function load() {
    const { data } = await http.get("/api/device-models", { params: { skip, limit: pageSize } });
    const list = (data.items || []) as Row[];
    const t = Number(data.total);
    if (list.length === 0 && t > 0 && page > 1) { setPage(1); return; }
    setItems(list); setTotal(Number.isFinite(t) ? t : 0);
  }

  useEffect(() => { void load(); }, [page, pageSize]);

  function openAdd() { setMode("add"); setEditingId(null); form.resetFields(); form.setFieldsValue({ status: DEVICE_MODEL_STATUS[0] }); setDlg(true); }
  function openEdit(row: Row) {
    setMode("edit"); setEditingId(String(row._id));
    form.setFieldsValue({ name: row.name, description: row.description || "", status: row.status });
    setDlg(true);
  }

  async function save() {
    const vals = await form.validateFields();
    if (mode === "add") await http.post("/api/device-models", vals);
    else if (editingId) await http.put(`/api/device-models/${editingId}`, vals);
    setDlg(false); message.success("已保存"); await load();
  }

  async function remove(row: Row) {
    Modal.confirm({ title: "确定删除该设备型号？", okType: "danger", onOk: async () => {
      await http.delete(`/api/device-models/${row._id}`); message.success("已删除"); await load();
    }});
  }

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total, pageSizeOptions: [10, 20, 50, 100], showSizeChanger: true,
    showTotal: (t) => `共 ${t} 条`,
    onChange: (p, ps) => { if (ps !== pageSize) { setPageSize(ps); setPage(1); } else setPage(p); },
  };

  const columns = [
    { title: "序号", width: 72, align: "center" as const, render: (_: unknown, __: unknown, i: number) => reverseSerialIndex(total, skip, i) },
    { title: "型号ID", dataIndex: "_id", width: 200 },
    { title: "型号名称", dataIndex: "name" },
    { title: "描述", dataIndex: "description", ellipsis: true },
    { title: "状态", dataIndex: "status", width: 100 },
    { title: "创建时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.created_at) },
    { title: "更新时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.updated_at) },
    ...(canWrite ? [{ title: "操作", width: 160, fixed: "right" as const, render: (_: unknown, row: Row) => (<><Button type="link" onClick={() => openEdit(row)}>修改</Button><Button type="link" danger onClick={() => remove(row)}>删除</Button></>) }] : []),
  ];

  return (
    <Card title={<div style={{ display: "flex", justifyContent: "space-between" }}><span>设备型号</span>{canWrite && <Button type="primary" onClick={openAdd}>添加型号</Button>}</div>}>
      <Table rowKey="_id" dataSource={items} columns={columns} pagination={pagination} bordered size="small" scroll={{ x: "max-content" }} />
      <Modal title={mode === "add" ? "添加设备型号" : "修改设备型号"} open={dlg} onOk={save} onCancel={() => setDlg(false)} afterClose={() => form.resetFields()}>
        <Form form={form} labelCol={{ span: 6 }}>
          <Form.Item label="型号名称" name="name" rules={[{ required: true }]}><Input /></Form.Item>
          <Form.Item label="描述" name="description"><Input.TextArea /></Form.Item>
          <Form.Item label="状态" name="status" rules={[{ required: true }]}>
            <Select options={DEVICE_MODEL_STATUS.map((s) => ({ value: s, label: s }))} />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  );
}
