// frontend/src/views/EvalTemplatesView.vue
<template>
  <el-card>
    <template #header>
      <div class="row">
        <span>世界模型素材库 / 评测模板</span>
        <el-button v-if="canWrite" type="primary" @click="openCreate">新建模板</el-button>
      </div>
    </template>

    <el-table :data="items" row-key="_id" border stripe>
      <el-table-column label="序号" width="72" align="center">
        <template #default="{ $index }">{{ revIdx($index) }}</template>
      </el-table-column>
      <el-table-column prop="_id" label="模板ID" width="220" show-overflow-tooltip />
      <el-table-column prop="name" label="模板名称" width="160" show-overflow-tooltip />
      <el-table-column prop="description" label="模板描述" min-width="180" show-overflow-tooltip />
      <el-table-column prop="status" label="模板状态" width="100" />
      <el-table-column prop="version" label="模板版本号" width="100" />
      <el-table-column label="步骤(k:v)" min-width="220" show-overflow-tooltip>
        <template #default="{ row }">
          {{ stepsSummary(row) }}
        </template>
      </el-table-column>
      <el-table-column label="模板创建时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="模板更新时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
      </el-table-column>
      <el-table-column prop="created_by" label="模板创建人" width="120" show-overflow-tooltip />
      <el-table-column prop="updated_by" label="模板更新人" width="120" show-overflow-tooltip />
      <el-table-column v-if="canWrite" label="操作" width="140" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openEdit(row)">编辑</el-button>
          <el-button link type="danger" @click="removeRow(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      class="table-pager"
    />

    <el-dialog v-model="dlg" :title="editingId ? '编辑评测模板' : '新建评测模板'" width="760px">
      <el-form :model="form" label-width="120px">
        <el-form-item label="模板名称" required>
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="模板描述">
          <el-input v-model="form.description" type="textarea" :rows="3" />
        </el-form-item>
        <el-form-item label="模板状态" required>
          <el-select v-model="form.status" style="width: 220px">
            <el-option v-for="s in EVAL_TEMPLATE_STATUS" :key="s" :label="s" :value="s" />
          </el-select>
        </el-form-item>
        <el-form-item label="模板版本号" required>
          <el-input v-model="form.version" style="width: 220px" placeholder="如 1.0（一位小数）" />
        </el-form-item>
        <el-divider content-position="left">步骤键值对（k=步骤名称，v=步骤分值）</el-divider>
        <div class="step-head">
          <span>步骤ID</span>
          <span>步骤名称(k)</span>
          <span>步骤分值(v)</span>
          <span />
        </div>
        <div v-for="(s, idx) in form.steps" :key="idx" class="step-row">
          <el-input :model-value="String(s.step_id)" readonly />
          <el-input v-model="s.name" placeholder="例如：抓取位置正确性" />
          <el-input-number
            v-model="s.max_score"
            :min="0.01"
            :max="1000000"
            :precision="2"
            controls-position="right"
            style="width: 160px"
          />
          <el-button link type="danger" @click="removeStep(idx)">删除</el-button>
        </div>
        <div class="step-foot">
          <el-button plain @click="addStep">添加步骤</el-button>
          <span class="muted">总分固定 100，新增/删除步骤时自动均分</span>
        </div>
      </el-form>
      <template #footer>
        <el-button @click="dlg = false">取消</el-button>
        <el-button type="primary" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import http from "@/api/http";
import { canWriteEvalTemplate } from "@/stores/auth";
import { EVAL_TEMPLATE_STATUS } from "@/constants/options";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type StepKV = { step_id: number; name: string; max_score: number };

const canWrite = computed(() => canWriteEvalTemplate());
const items = ref<Record<string, unknown>[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = ref(DEFAULT_PAGE_SIZE);
const skip = computed(() => skipForPage(page.value, pageSize.value));

const dlg = ref(false);
const editingId = ref<string | null>(null);

const form = reactive({
  name: "",
  description: "",
  status: EVAL_TEMPLATE_STATUS[0],
  version: "1.0",
  steps: [] as StepKV[],
});

function revIdx($index: number) {
  return reverseSerialIndex(total.value, skip.value, $index);
}

function rebalanceStepScores() {
  const n = form.steps.length;
  if (n <= 0) return;
  const unit = Number((100 / n).toFixed(2));
  let sum = 0;
  for (let i = 0; i < n; i += 1) {
    if (i < n - 1) {
      form.steps[i].max_score = unit;
      sum += unit;
    } else {
      form.steps[i].max_score = Number((100 - sum).toFixed(2));
    }
  }
}

function resequenceStepIds() {
  for (let i = 0; i < form.steps.length; i += 1) {
    form.steps[i].step_id = i + 1;
  }
}

function addStep() {
  form.steps.push({ step_id: form.steps.length + 1, name: "", max_score: 0 });
  resequenceStepIds();
  rebalanceStepScores();
}

function removeStep(idx: number) {
  form.steps.splice(idx, 1);
  resequenceStepIds();
  rebalanceStepScores();
}

function stepsSummary(row: Record<string, unknown>) {
  const raw = row.steps as { step_id?: unknown; name?: unknown; max_score?: unknown }[] | undefined;
  if (!Array.isArray(raw) || raw.length === 0) return "—";
  return raw
    .map((s) => `${String(s?.step_id ?? "")}.${String(s?.name ?? "")}:${String(s?.max_score ?? "")}`)
    .filter((x) => x !== ":")
    .join("；");
}

async function load() {
  const { data } = await http.get("/api/evaluations/step-templates", {
    params: { skip: skip.value, limit: pageSize.value },
  });
  const list = (data.items || []) as Record<string, unknown>[];
  const t = Number((data as { total?: number }).total);
  if (list.length === 0 && t > 0 && page.value > 1) {
    page.value = 1;
    return load();
  }
  items.value = list;
  total.value = Number.isFinite(t) ? t : 0;
}

function resetForm() {
  form.name = "";
  form.description = "";
  form.status = EVAL_TEMPLATE_STATUS[0];
  form.version = "1.0";
  form.steps.length = 0;
}

function openCreate() {
  editingId.value = null;
  resetForm();
  dlg.value = true;
}

function openEdit(row: Record<string, unknown>) {
  editingId.value = String(row._id);
  form.name = String(row.name || "");
  form.description = String(row.description || "");
  form.status = String(row.status || EVAL_TEMPLATE_STATUS[0]);
  form.version = String(row.version || "1.0");
  form.steps.length = 0;
  const raw = row.steps as StepKV[] | undefined;
  if (Array.isArray(raw)) {
    for (const s of raw) {
      form.steps.push({
        step_id: Number((s as { step_id?: unknown }).step_id) || form.steps.length + 1,
        name: String(s.name ?? ""),
        max_score: Number(s.max_score) > 0 ? Number(s.max_score) : 10,
      });
    }
    resequenceStepIds();
  }
  dlg.value = true;
}

async function save() {
  const name = form.name.trim();
  if (!name) {
    ElMessage.warning("请填写模板名称");
    return;
  }
  const steps = form.steps
    .map((s) => ({ step_id: s.step_id, name: String(s.name || "").trim(), max_score: Number(s.max_score) }))
    .filter((s) => s.name && s.max_score > 0);

  const body = {
    name,
    description: form.description,
    status: form.status,
    version: form.version,
    steps,
  };
  if (editingId.value) {
    await http.put(`/api/evaluations/step-templates/${editingId.value}`, body);
  } else {
    await http.post("/api/evaluations/step-templates", body);
  }
  dlg.value = false;
  ElMessage.success("已保存");
  await load();
}

async function removeRow(row: Record<string, unknown>) {
  await ElMessageBox.confirm("确定删除该评测模板？", "删除", { type: "warning" });
  await http.delete(`/api/evaluations/step-templates/${row._id}`);
  ElMessage.success("已删除");
  await load();
}

watch(pageSize, () => {
  page.value = 1;
});
watch(
  [page, pageSize],
  () => {
    void load();
  },
  { immediate: true }
);
</script>

<style scoped>
.row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.step-head,
.step-row {
  display: grid;
  grid-template-columns: 96px 1fr 170px 72px;
  gap: 10px;
  align-items: center;
}

.step-head {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  margin-bottom: 8px;
}

.step-row {
  margin-bottom: 8px;
}

.step-foot {
  display: flex;
  gap: 10px;
  align-items: center;
}
</style>

// frontend/src/views/EvalTemplatesView.tsx
import { useEffect, useMemo, useState } from "react";
import { Table, Button, Modal, Form, Input, Select, InputNumber, Divider, message, Card, Space } from "antd";
import type { TablePaginationConfig } from "antd";
import http from "@/api/http";
import { EVAL_TEMPLATE_STATUS } from "@/constants/options";
import { canWriteEvalTemplate } from "@/stores/auth";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type Row = Record<string, unknown>;
type StepKV = { step_id: number; name: string; max_score: number };

export default function EvalTemplatesView() {
  const [items, setItems] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [dlg, setDlg] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [steps, setSteps] = useState<StepKV[]>([]);
  const [form] = Form.useForm();
  const canWrite = canWriteEvalTemplate();
  const skip = useMemo(() => skipForPage(page, pageSize), [page, pageSize]);

  async function load() {
    const { data } = await http.get("/api/evaluations/step-templates", { params: { skip, limit: pageSize } });
    const list = (data.items || []) as Row[];
    const t = Number(data.total);
    if (list.length === 0 && t > 0 && page > 1) { setPage(1); return; }
    setItems(list); setTotal(Number.isFinite(t) ? t : 0);
  }

  useEffect(() => { void load(); }, [page, pageSize]);

  function rebalance(arr: StepKV[]): StepKV[] {
    const n = arr.length;
    if (n === 0) return arr;
    const unit = Number((100 / n).toFixed(2));
    let sum = 0;
    return arr.map((s, i) => {
      const score = i < n - 1 ? unit : Number((100 - sum).toFixed(2));
      sum += unit;
      return { ...s, step_id: i + 1, max_score: score };
    });
  }

  function addStep() { setSteps((prev) => rebalance([...prev, { step_id: 0, name: "", max_score: 0 }])); }
  function insertBefore(idx: number) { setSteps((prev) => { const next = [...prev]; next.splice(idx, 0, { step_id: 0, name: "", max_score: 0 }); return rebalance(next); }); }
  function removeStep(idx: number) { setSteps((prev) => rebalance(prev.filter((_, i) => i !== idx))); }
  function updateStep(idx: number, field: keyof StepKV, val: string | number) {
    setSteps((prev) => prev.map((s, i) => i === idx ? { ...s, [field]: val } : s));
  }

  function openCreate() { setEditingId(null); form.resetFields(); form.setFieldsValue({ status: EVAL_TEMPLATE_STATUS[0], version: "1.0" }); setSteps([]); setDlg(true); }
  function openEdit(row: Row) {
    setEditingId(String(row._id));
    form.setFieldsValue({ name: row.name, description: row.description || "", status: row.status, version: row.version });
    const raw = row.steps as StepKV[] | undefined;
    setSteps(Array.isArray(raw) ? raw.map((s, i) => ({ step_id: i + 1, name: String(s.name ?? ""), max_score: Number(s.max_score) || 10 })) : []);
    setDlg(true);
  }

  async function save() {
    const vals = await form.validateFields();
    if (!vals.name?.trim()) { message.warning("请填写模板名称"); return; }
    const body = { ...vals, steps: steps.filter((s) => s.name && s.max_score > 0) };
    if (editingId) await http.put(`/api/evaluations/step-templates/${editingId}`, body);
    else await http.post("/api/evaluations/step-templates", body);
    setDlg(false); message.success("已保存"); await load();
  }

  async function removeRow(row: Row) {
    Modal.confirm({ title: "确定删除该评测模板？", okType: "danger", onOk: async () => {
      await http.delete(`/api/evaluations/step-templates/${row._id}`); message.success("已删除"); await load();
    }});
  }

  function stepsSummary(row: Row) {
    const raw = row.steps as { step_id?: unknown; name?: unknown; max_score?: unknown }[] | undefined;
    if (!Array.isArray(raw) || !raw.length) return "—";
    return raw.map((s) => `${s.step_id}.${s.name}:${s.max_score}`).filter((x) => x !== ":").join("；");
  }

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total, pageSizeOptions: [10, 20, 50, 100], showSizeChanger: true,
    showTotal: (t) => `共 ${t} 条`,
    onChange: (p, ps) => { if (ps !== pageSize) { setPageSize(ps); setPage(1); } else setPage(p); },
  };

  const columns = [
    { title: "序号", width: 72, align: "center" as const, render: (_: unknown, __: unknown, i: number) => reverseSerialIndex(total, skip, i) },
    { title: "模板ID", dataIndex: "_id", width: 220, ellipsis: true },
    { title: "模板名称", dataIndex: "name", width: 160, ellipsis: true },
    { title: "模板描述", dataIndex: "description", ellipsis: true },
    { title: "状态", dataIndex: "status", width: 100 },
    { title: "版本号", dataIndex: "version", width: 100 },
    { title: "步骤(k:v)", ellipsis: true, render: (_: unknown, row: Row) => stepsSummary(row) },
    { title: "创建时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.created_at) },
    { title: "更新时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.updated_at) },
    ...(canWrite ? [{ title: "操作", width: 140, fixed: "right" as const, render: (_: unknown, row: Row) => (<><Button type="link" onClick={() => openEdit(row)}>编辑</Button><Button type="link" danger onClick={() => removeRow(row)}>删除</Button></>) }] : []),
  ];

  return (
    <Card title={<div style={{ display: "flex", justifyContent: "space-between" }}><span>世界模型素材库 / 评测模板</span>{canWrite && <Button type="primary" onClick={openCreate}>新建模板</Button>}</div>}>
      <Table rowKey="_id" dataSource={items} columns={columns} pagination={pagination} bordered size="small" scroll={{ x: "max-content" }} />
      <Modal title={editingId ? "编辑评测模板" : "新建评测模板"} open={dlg} onOk={save} onCancel={() => setDlg(false)} width={760} afterClose={() => form.resetFields()}>
        <Form form={form} labelCol={{ span: 5 }}>
          <Form.Item label="模板名称" name="name" rules={[{ required: true }]}><Input /></Form.Item>
          <Form.Item label="模板描述" name="description"><Input.TextArea rows={3} /></Form.Item>
          <Form.Item label="模板状态" name="status" rules={[{ required: true }]}><Select style={{ width: 220 }} options={EVAL_TEMPLATE_STATUS.map((s) => ({ value: s, label: s }))} /></Form.Item>
          <Form.Item label="版本号" name="version" rules={[{ required: true }]}><Input style={{ width: 220 }} /></Form.Item>
        </Form>
        <Divider>步骤键值对（k=步骤名称，v=步骤分值）</Divider>
        <div style={{ display: "grid", gridTemplateColumns: "96px 1fr 170px 120px", gap: 10, fontSize: 12, color: "#8c8c8c", marginBottom: 8 }}>
          <span>步骤ID</span><span>步骤名称(k)</span><span>步骤分值(v)</span><span>操作</span>
        </div>
        {steps.map((s, idx) => (
          <div key={idx} style={{ display: "grid", gridTemplateColumns: "96px 1fr 170px 120px", gap: 10, alignItems: "center", marginBottom: 8 }}>
            <Input value={String(s.step_id)} readOnly />
            <Input value={s.name} onChange={(e) => updateStep(idx, "name", e.target.value)} placeholder="步骤名称" />
            <InputNumber value={s.max_score} min={0.01} max={1000000} precision={2} onChange={(v) => updateStep(idx, "max_score", v ?? 0)} style={{ width: "100%" }} />
            <Space size={4}>
              <Button type="link" onClick={() => insertBefore(idx)} title="在此步之前插入">+</Button>
              <Button type="link" danger onClick={() => removeStep(idx)}>删除</Button>
            </Space>
          </div>
        ))}
        <div style={{ display: "flex", gap: 10, alignItems: "center", marginTop: 8 }}>
          <Button onClick={addStep}>添加步骤</Button>
          <span style={{ color: "#8c8c8c", fontSize: 12 }}>总分固定 100，新增/删除步骤时自动均分</span>
        </div>
      </Modal>
    </Card>
  );
}
