// frontend/src/views/RobotsView.tsx
import { useEffect, useMemo, useState } from "react";
import { Table, Button, Modal, Form, Input, Select, message, Card } from "antd";
import type { TablePaginationConfig } from "antd";
import http from "@/api/http";
import { ROBOT_STATUS } from "@/constants/options";
import { canWriteRobot } from "@/stores/auth";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type Row = Record<string, unknown>;
type DeviceModelOption = { id: string; name: string; status: string };

export default function RobotsView() {
  const [items, setItems] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [formDlg, setFormDlg] = useState(false);
  const [detailDlg, setDetailDlg] = useState(false);
  const [mode, setMode] = useState<"add" | "edit">("add");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [detailId, setDetailId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [detailSaving, setDetailSaving] = useState(false);
  const [deviceModelOptions, setDeviceModelOptions] = useState<DeviceModelOption[]>([]);
  const [form] = Form.useForm();
  const [detailForm] = Form.useForm();
  const canWrite = canWriteRobot();
  const skip = useMemo(() => skipForPage(page, pageSize), [page, pageSize]);

  async function loadDeviceModelOptions() {
    try {
      const { data } = await http.get("/api/robots/device-model-options");
      setDeviceModelOptions((data.items || []) as DeviceModelOption[]);
    } catch { setDeviceModelOptions([]); }
  }

  function resolveDeviceModelId(row: Row): string {
    const id = row.device_model_id != null ? String(row.device_model_id) : "";
    if (id) return id;
    const name = String(row.device_model || "").trim();
    return deviceModelOptions.find((m) => m.name === name)?.id ?? "";
  }

  async function load() {
    const { data } = await http.get("/api/robots", { params: { skip, limit: pageSize } });
    const list = (data.items || []) as Row[];
    const t = Number(data.total);
    if (list.length === 0 && t > 0 && page > 1) { setPage(1); return; }
    setItems(list); setTotal(Number.isFinite(t) ? t : 0);
  }

  useEffect(() => { void loadDeviceModelOptions(); }, []);
  useEffect(() => { void load(); }, [page, pageSize]);

  const dmOptions = deviceModelOptions.map((m) => ({ value: m.id, label: m.status ? `${m.name}（${m.status}）` : m.name }));

  function openAdd() {
    setMode("add"); setEditingId(null);
    form.resetFields(); form.setFieldsValue({ status: ROBOT_STATUS[0], version: "1.0" });
    setFormDlg(true);
  }

  function openEdit(row: Row) {
    setMode("edit"); setEditingId(String(row._id));
    form.setFieldsValue({ name: row.name, device_model_id: resolveDeviceModelId(row), status: row.status, version: row.version, details: row.details || "" });
    setFormDlg(true);
  }

  function openDetail(row: Row) {
    setDetailId(String(row._id));
    detailForm.setFieldsValue({ name: row.name, device_model_id: resolveDeviceModelId(row), device_model: row.device_model, status: row.status, version: row.version, details: row.details || "", created_at: formatDateTime(row.created_at), updated_at: formatDateTime(row.updated_at), created_by: row.created_by || "—", updated_by: row.updated_by || "—" });
    setDetailDlg(true);
  }

  async function saveForm() {
    const vals = await form.validateFields();
    if (!vals.device_model_id?.trim()) { message.warning("请选择设备型号"); return; }
    setSaving(true);
    try {
      if (mode === "add") await http.post("/api/robots", vals);
      else if (editingId) await http.put(`/api/robots/${editingId}`, vals);
      setFormDlg(false); message.success("已保存"); await load();
    } finally { setSaving(false); }
  }

  async function saveDetail() {
    if (!detailId || !canWrite) return;
    const vals = await detailForm.validateFields();
    if (!vals.device_model_id?.trim()) { message.warning("请选择设备型号"); return; }
    setDetailSaving(true);
    try {
      await http.put(`/api/robots/${detailId}`, { name: vals.name, device_model_id: vals.device_model_id, status: vals.status, version: vals.version, details: vals.details });
      message.success("已保存"); setDetailDlg(false); await load();
    } finally { setDetailSaving(false); }
  }

  async function remove(row: Row) {
    Modal.confirm({ title: `确定删除机器人「${row.name}」？`, okType: "danger", onOk: async () => {
      await http.delete(`/api/robots/${row._id}`); message.success("已删除"); await load();
    }});
  }

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total, pageSizeOptions: [10, 20, 50, 100], showSizeChanger: true,
    showTotal: (t) => `共 ${t} 条`,
    onChange: (p, ps) => { if (ps !== pageSize) { setPageSize(ps); setPage(1); } else setPage(p); },
  };

  const columns = [
    { title: "序号", width: 72, align: "center" as const, render: (_: unknown, __: unknown, i: number) => reverseSerialIndex(total, skip, i) },
    { title: "机器人ID", dataIndex: "_id", width: 200, ellipsis: true },
    { title: "机器人名称", dataIndex: "name" },
    { title: "设备型号", dataIndex: "device_model", width: 120 },
    { title: "状态", dataIndex: "status", width: 100 },
    { title: "版本号", dataIndex: "version", width: 100 },
    { title: "创建时间", width: 170, render: (_: unknown, row: Row) => formatDateTime(row.created_at) },
    { title: "更新时间", width: 170, render: (_: unknown, row: Row) => formatDateTime(row.updated_at) },
    { title: "详情", width: 100, fixed: "right" as const, render: (_: unknown, row: Row) => <Button type="link" onClick={() => openDetail(row)}>详情</Button> },
    ...(canWrite ? [{ title: "操作", width: 140, fixed: "right" as const, render: (_: unknown, row: Row) => (<><Button type="link" onClick={() => openEdit(row)}>编辑</Button><Button type="link" danger onClick={() => remove(row)}>删除</Button></>) }] : []),
  ];

  const formFields = (
    <Form.Item label="设备型号" name="device_model_id" rules={[{ required: true }]}>
      <Select options={dmOptions} showSearch filterOption={(i, o) => (o?.label ?? "").toLowerCase().includes(i.toLowerCase())} />
    </Form.Item>
  );

  return (
    <Card title={<div style={{ display: "flex", justifyContent: "space-between" }}><span>机器人管理</span>{canWrite && <Button type="primary" onClick={openAdd}>添加机器人</Button>}</div>}>
      <Table rowKey="_id" dataSource={items} columns={columns} pagination={pagination} bordered size="small" scroll={{ x: "max-content" }} />

      <Modal title={mode === "add" ? "添加机器人" : "修改机器人"} open={formDlg} onOk={saveForm} confirmLoading={saving} onCancel={() => setFormDlg(false)} afterClose={() => form.resetFields()}>
        <Form form={form} labelCol={{ span: 7 }}>
          <Form.Item label="机器人名称" name="name" rules={[{ required: true }]}><Input /></Form.Item>
          {formFields}
          <Form.Item label="机器人状态" name="status" rules={[{ required: true }]}><Select options={ROBOT_STATUS.map((s) => ({ value: s, label: s }))} /></Form.Item>
          <Form.Item label="版本号" name="version" rules={[{ required: true }]}><Input /></Form.Item>
          <Form.Item label="机器人详情" name="details"><Input.TextArea rows={4} /></Form.Item>
        </Form>
      </Modal>

      <Modal title="机器人详情" open={detailDlg} onOk={canWrite ? saveDetail : undefined} confirmLoading={detailSaving} onCancel={() => setDetailDlg(false)} footer={canWrite ? undefined : [<Button key="close" onClick={() => setDetailDlg(false)}>关闭</Button>]}>
        <Form form={detailForm} labelCol={{ span: 7 }}>
          <Form.Item label="机器人名称" name="name"><Input disabled={!canWrite} /></Form.Item>
          {canWrite
            ? <Form.Item label="设备型号" name="device_model_id"><Select options={dmOptions} showSearch /></Form.Item>
            : <Form.Item label="设备型号" name="device_model"><Input readOnly /></Form.Item>}
          <Form.Item label="机器人状态" name="status"><Select options={ROBOT_STATUS.map((s) => ({ value: s, label: s }))} disabled={!canWrite} /></Form.Item>
          <Form.Item label="版本号" name="version"><Input disabled={!canWrite} /></Form.Item>
          <Form.Item label="机器人详情" name="details"><Input.TextArea rows={5} disabled={!canWrite} /></Form.Item>
          <Form.Item label="创建时间" name="created_at"><Input readOnly /></Form.Item>
          <Form.Item label="更新时间" name="updated_at"><Input readOnly /></Form.Item>
          <Form.Item label="创建人" name="created_by"><Input readOnly /></Form.Item>
          <Form.Item label="更新人" name="updated_by"><Input readOnly /></Form.Item>
        </Form>
      </Modal>
    </Card>
  );
}

// frontend/src/views/RobotsView.vue
<template>
  <el-card>
    <template #header>
      <div class="row">
        <span>机器人管理</span>
        <el-button v-if="canWrite" type="primary" @click="openAdd">添加机器人</el-button>
      </div>
    </template>

    <el-table :data="items" border stripe row-key="_id">
      <el-table-column label="序号" width="72" align="center">
        <template #default="{ $index }">{{ revIdx($index) }}</template>
      </el-table-column>
      <el-table-column prop="_id" label="机器人ID" width="200" show-overflow-tooltip />
      <el-table-column prop="name" label="机器人名称" min-width="140" />
      <el-table-column prop="device_model" label="设备型号" width="120" />
      <el-table-column prop="status" label="机器人状态" width="100" />
      <el-table-column prop="version" label="机器人版本号" width="120" />
      <el-table-column label="创建时间" width="170">
        <template #default="{ row }">{{ formatDateTime(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="更新时间" width="170">
        <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
      </el-table-column>
      <el-table-column prop="created_by" label="创建人" width="100" show-overflow-tooltip />
      <el-table-column prop="updated_by" label="更新人" width="100" show-overflow-tooltip />
      <el-table-column label="机器人详情" width="100" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openDetail(row)">详情</el-button>
        </template>
      </el-table-column>
      <el-table-column v-if="canWrite" label="操作" width="140" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openEdit(row)">编辑</el-button>
          <el-button link type="danger" @click="remove(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      class="table-pager"
    />

    <el-dialog v-model="formDlg" :title="formDlgTitle" width="560px">
      <el-form :model="form" label-width="120px">
        <el-form-item label="机器人名称" required>
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="设备型号" required>
          <el-select
            v-model="form.device_model_id"
            filterable
            clearable
            placeholder="请选择设备型号"
            style="width: 100%"
          >
            <el-option
              v-for="m in deviceModelOptions"
              :key="m.id"
              :label="m.status ? `${m.name}（${m.status}）` : m.name"
              :value="m.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="机器人状态" required>
          <el-select v-model="form.status" style="width: 100%">
            <el-option v-for="s in ROBOT_STATUS" :key="s" :label="s" :value="s" />
          </el-select>
        </el-form-item>
        <el-form-item label="机器人版本号" required>
          <el-input v-model="form.version" placeholder="如 1.0、2.0（一位小数）" />
        </el-form-item>
        <el-form-item label="机器人详情">
          <el-input v-model="form.details" type="textarea" :rows="4" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="formDlg = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="saveForm">保存</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="detailDlg" title="机器人详情" width="560px">
      <el-form :model="detailForm" label-width="120px">
        <el-form-item label="机器人名称">
          <el-input v-model="detailForm.name" :disabled="!canWrite" />
        </el-form-item>
        <el-form-item label="设备型号">
          <el-select
            v-if="canWrite"
            v-model="detailForm.device_model_id"
            filterable
            clearable
            placeholder="请选择设备型号"
            style="width: 100%"
          >
            <el-option
              v-for="m in deviceModelOptions"
              :key="m.id"
              :label="m.status ? `${m.name}（${m.status}）` : m.name"
              :value="m.id"
            />
          </el-select>
          <el-input v-else :model-value="detailForm.device_model" readonly />
        </el-form-item>
        <el-form-item label="机器人状态">
          <el-select v-model="detailForm.status" style="width: 100%" :disabled="!canWrite">
            <el-option v-for="s in ROBOT_STATUS" :key="s" :label="s" :value="s" />
          </el-select>
        </el-form-item>
        <el-form-item label="机器人版本号">
          <el-input v-model="detailForm.version" :disabled="!canWrite" placeholder="如 1.0" />
        </el-form-item>
        <el-form-item label="机器人详情">
          <el-input v-model="detailForm.details" type="textarea" :rows="5" :disabled="!canWrite" />
        </el-form-item>
        <el-form-item label="创建时间">
          <el-input :model-value="formatDateTime(detailForm.created_at)" readonly />
        </el-form-item>
        <el-form-item label="更新时间">
          <el-input :model-value="formatDateTime(detailForm.updated_at)" readonly />
        </el-form-item>
        <el-form-item label="创建人">
          <el-input :model-value="detailForm.created_by || '—'" readonly />
        </el-form-item>
        <el-form-item label="更新人">
          <el-input :model-value="detailForm.updated_by || '—'" readonly />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="detailDlg = false">关闭</el-button>
        <el-button v-if="canWrite" type="primary" :loading="detailSaving" @click="saveDetail">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import http from "@/api/http";
import { ElMessage, ElMessageBox } from "element-plus";
import { ROBOT_STATUS } from "@/constants/options";
import { canWriteRobot } from "@/stores/auth";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

const items = ref<Record<string, unknown>[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = ref(DEFAULT_PAGE_SIZE);
const skip = computed(() => skipForPage(page.value, pageSize.value));

function revIdx($index: number) {
  return reverseSerialIndex(total.value, skip.value, $index);
}
const deviceModelOptions = ref<{ id: string; name: string; status: string }[]>([]);
const canWrite = computed(() => canWriteRobot());

const formDlg = ref(false);
const formMode = ref<"add" | "edit">("add");
const editingId = ref<string | null>(null);
const saving = ref(false);

const form = reactive({
  name: "",
  device_model_id: "",
  status: ROBOT_STATUS[0],
  version: "1.0",
  details: "",
});

const formDlgTitle = computed(() => (formMode.value === "add" ? "添加机器人" : "修改机器人"));

const detailDlg = ref(false);
const detailId = ref<string | null>(null);
const detailSaving = ref(false);
const detailForm = reactive({
  name: "",
  device_model: "",
  device_model_id: "",
  status: ROBOT_STATUS[0],
  version: "1.0",
  details: "",
  created_at: "",
  updated_at: "",
  created_by: "",
  updated_by: "",
});

async function loadDeviceModelOptions() {
  try {
    const { data } = await http.get("/api/robots/device-model-options");
    deviceModelOptions.value = (data.items || []) as {
      id: string;
      name: string;
      status: string;
    }[];
  } catch {
    deviceModelOptions.value = [];
  }
}

function resolveDeviceModelIdFromRow(row: Record<string, unknown>): string {
  const id = row.device_model_id != null ? String(row.device_model_id) : "";
  if (id) return id;
  const legacyName = String(row.device_model || "").trim();
  if (!legacyName) return "";
  const hit = deviceModelOptions.value.find((m) => m.name === legacyName);
  return hit ? hit.id : "";
}

async function load() {
  const { data } = await http.get("/api/robots", {
    params: { skip: skip.value, limit: pageSize.value },
  });
  const list = (data.items || []) as Record<string, unknown>[];
  const t = Number((data as { total?: number }).total);
  if (list.length === 0 && t > 0 && page.value > 1) {
    page.value = 1;
    return load();
  }
  items.value = list;
  total.value = Number.isFinite(t) ? t : 0;
}

function openAdd() {
  formMode.value = "add";
  editingId.value = null;
  Object.assign(form, {
    name: "",
    device_model_id: "",
    status: ROBOT_STATUS[0],
    version: "1.0",
    details: "",
  });
  formDlg.value = true;
}

function openEdit(row: Record<string, unknown>) {
  formMode.value = "edit";
  editingId.value = String(row._id);
  form.name = String(row.name || "");
  form.device_model_id = resolveDeviceModelIdFromRow(row);
  form.status = String(row.status || ROBOT_STATUS[0]);
  form.version = String(row.version || "1.0");
  form.details = String(row.details || "");
  formDlg.value = true;
}

function openDetail(row: Record<string, unknown>) {
  detailId.value = String(row._id);
  detailForm.name = String(row.name || "");
  detailForm.device_model = String(row.device_model || "");
  detailForm.device_model_id = resolveDeviceModelIdFromRow(row);
  detailForm.status = String(row.status || ROBOT_STATUS[0]);
  detailForm.version = String(row.version || "1.0");
  detailForm.details = String(row.details || "");
  detailForm.created_at = String(row.created_at || "");
  detailForm.updated_at = String(row.updated_at || "");
  detailForm.created_by = String(row.created_by || "");
  detailForm.updated_by = String(row.updated_by || "");
  detailDlg.value = true;
}

async function saveForm() {
  if (!form.device_model_id?.trim()) {
    ElMessage.warning("请选择设备型号");
    return;
  }
  saving.value = true;
  try {
    if (formMode.value === "add") {
      await http.post("/api/robots", {
        name: form.name,
        device_model_id: form.device_model_id,
        status: form.status,
        version: form.version,
        details: form.details,
      });
    } else if (editingId.value) {
      await http.put(`/api/robots/${editingId.value}`, {
        name: form.name,
        device_model_id: form.device_model_id,
        status: form.status,
        version: form.version,
        details: form.details,
      });
    }
    formDlg.value = false;
    ElMessage.success("已保存");
    await load();
  } finally {
    saving.value = false;
  }
}

async function saveDetail() {
  if (!detailId.value || !canWrite.value) return;
  if (!detailForm.device_model_id?.trim()) {
    ElMessage.warning("请选择设备型号");
    return;
  }
  detailSaving.value = true;
  try {
    await http.put(`/api/robots/${detailId.value}`, {
      name: detailForm.name,
      device_model_id: detailForm.device_model_id,
      status: detailForm.status,
      version: detailForm.version,
      details: detailForm.details,
    });
    ElMessage.success("已保存");
    detailDlg.value = false;
    await load();
  } finally {
    detailSaving.value = false;
  }
}

async function remove(row: Record<string, unknown>) {
  await ElMessageBox.confirm(`确定删除机器人「${row.name}」？`, "删除", { type: "warning" });
  await http.delete(`/api/robots/${row._id}`);
  ElMessage.success("已删除");
  await load();
}

watch(pageSize, () => {
  page.value = 1;
});
watch(
  [page, pageSize],
  () => {
    void load();
  },
  { immediate: true }
);

onMounted(async () => {
  await loadDeviceModelOptions();
});
</script>

<style scoped>
.row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>
