// frontend/src/views/RolesView.tsx
import { useEffect, useMemo, useState } from "react";
import { Table, Button, Modal, Form, Input, Checkbox, Tag, message, Card } from "antd";
import type { TablePaginationConfig } from "antd";
import http from "@/api/http";
import { ROLE_MODULE_OPTIONS } from "@/constants/options";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type Row = Record<string, unknown>;
const moduleLabelMap = Object.fromEntries(ROLE_MODULE_OPTIONS.map((o) => [o.value, o.label]));

export default function RolesView() {
  const [items, setItems] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [dlg, setDlg] = useState(false);
  const [mode, setMode] = useState<"add" | "edit">("add");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form] = Form.useForm();
  const skip = useMemo(() => skipForPage(page, pageSize), [page, pageSize]);

  async function load() {
    const { data } = await http.get("/api/roles", { params: { skip, limit: pageSize } });
    const list = (data.items || []) as Row[];
    const t = Number(data.total);
    if (list.length === 0 && t > 0 && page > 1) { setPage(1); return; }
    setItems(list); setTotal(Number.isFinite(t) ? t : 0);
  }

  useEffect(() => { void load(); }, [page, pageSize]);

  function openAdd() {
    setMode("add"); setEditingId(null); form.resetFields(); setDlg(true);
  }

  function openEdit(row: Row) {
    setMode("edit"); setEditingId(String(row._id));
    form.setFieldsValue({ name: row.name, code: row.code, description: row.description || "", modules: Array.isArray(row.modules) ? row.modules : [] });
    setDlg(true);
  }

  async function save() {
    const vals = await form.validateFields();
    if (!vals.modules?.length) { message.warning("请至少勾选一个系统模块权限"); return; }
    if (mode === "add") {
      await http.post("/api/roles", vals);
    } else if (editingId) {
      await http.put(`/api/roles/${editingId}`, { name: vals.name, description: vals.description, modules: vals.modules });
    }
    setDlg(false); message.success("已保存"); await load();
  }

  async function remove(row: Row) {
    Modal.confirm({ title: "确定删除该角色？", okType: "danger", onOk: async () => {
      await http.delete(`/api/roles/${row._id}`);
      message.success("已删除"); await load();
    }});
  }

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total, pageSizeOptions: [10, 20, 50, 100], showSizeChanger: true,
    showTotal: (t) => `共 ${t} 条`,
    onChange: (p, ps) => { if (ps !== pageSize) { setPageSize(ps); setPage(1); } else setPage(p); },
  };

  const columns = [
    { title: "序号", width: 72, align: "center" as const, render: (_: unknown, __: unknown, i: number) => reverseSerialIndex(total, skip, i) },
    { title: "角色ID", dataIndex: "_id", width: 200 },
    { title: "名称", dataIndex: "name" },
    { title: "编码", dataIndex: "code" },
    { title: "描述", dataIndex: "description", ellipsis: true },
    { title: "模块权限", render: (_: unknown, row: Row) => {
      const mods = Array.isArray(row.modules) ? row.modules as string[] : [];
      return mods.length ? mods.map((m) => <Tag key={m} style={{ marginBottom: 2 }}>{moduleLabelMap[m] || m}</Tag>) : <span style={{ color: "#bfbfbf" }}>—</span>;
    }},
    { title: "创建时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.created_at) },
    { title: "更新时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.updated_at) },
    { title: "操作", width: 160, fixed: "right" as const, render: (_: unknown, row: Row) => (<><Button type="link" onClick={() => openEdit(row)}>修改</Button><Button type="link" danger onClick={() => remove(row)}>删除</Button></>) },
  ];

  return (
    <Card title={<div style={{ display: "flex", justifyContent: "space-between" }}><span>角色管理</span><Button type="primary" onClick={openAdd}>添加角色</Button></div>}>
      <Table rowKey="_id" dataSource={items} columns={columns} pagination={pagination} bordered size="small" scroll={{ x: "max-content" }} />
      <Modal title={mode === "add" ? "添加角色" : "修改角色"} open={dlg} onOk={save} onCancel={() => setDlg(false)} afterClose={() => form.resetFields()} width={600}>
        <Form form={form} labelCol={{ span: 6 }}>
          <Form.Item label="名称" name="name" rules={[{ required: true }]}>
            <Input disabled={mode === "edit"} />
          </Form.Item>
          {mode === "add" && <Form.Item label="编码" name="code" rules={[{ required: true }]}><Input placeholder="如 custom_role" /></Form.Item>}
          <Form.Item label="描述" name="description"><Input.TextArea /></Form.Item>
          <Form.Item label="模块权限" name="modules" rules={[{ required: true }]}>
            <Checkbox.Group options={ROLE_MODULE_OPTIONS} style={{ display: "flex", flexWrap: "wrap", gap: 8 }} />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  );
}

// frontend/src/views/RolesView.vue
<template>
  <el-card>
    <template #header>
      <div class="row">
        <span>角色管理</span>
        <el-button type="primary" @click="openAdd">添加角色</el-button>
      </div>
    </template>
    <el-table :data="items" border stripe row-key="_id">
      <el-table-column label="序号" width="72" align="center">
        <template #default="{ $index }">{{ revIdx($index) }}</template>
      </el-table-column>
      <el-table-column prop="_id" label="角色ID" width="200" />
      <el-table-column prop="name" label="名称" />
      <el-table-column prop="code" label="编码" />
      <el-table-column prop="description" label="描述" show-overflow-tooltip min-width="120" />
      <el-table-column label="模块权限" min-width="200">
        <template #default="{ row }">
          <el-tag v-for="m in moduleLabels(row)" :key="m" size="small" class="tag">{{ m }}</el-tag>
          <span v-if="!moduleLabels(row).length" class="muted">—</span>
        </template>
      </el-table-column>
      <el-table-column label="创建时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="更新时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
      </el-table-column>
      <el-table-column label="操作" width="160" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openEdit(row)">修改</el-button>
          <el-button link type="danger" @click="remove(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      class="table-pager"
    />

    <el-dialog v-model="dlg" :title="dlgTitle" width="600px" @closed="resetForm">
      <el-form :model="form" label-width="100px">
        <el-form-item label="名称" required>
          <el-input v-model="form.name" :disabled="mode === 'edit'" />
        </el-form-item>
        <el-form-item v-if="mode === 'add'" label="编码" required>
          <el-input v-model="form.code" placeholder="如 custom_role" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="form.description" type="textarea" />
        </el-form-item>
        <el-form-item label="模块权限" required>
          <el-checkbox-group v-model="form.modules">
            <el-checkbox v-for="o in ROLE_MODULE_OPTIONS" :key="o.value" :label="o.value">
              {{ o.label }}
            </el-checkbox>
          </el-checkbox-group>
          <p class="hint">勾选后，使用该角色的账号登录才可看到对应菜单；接口权限与登录令牌一并下发。</p>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dlg = false">取消</el-button>
        <el-button type="primary" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup lang="ts">
import { reactive, ref, computed, watch } from "vue";
import http from "@/api/http";
import { ElMessage, ElMessageBox } from "element-plus";
import { formatDateTime } from "@/utils/datetime";
import { ROLE_MODULE_OPTIONS } from "@/constants/options";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

const items = ref<Record<string, unknown>[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = ref(DEFAULT_PAGE_SIZE);
const skip = computed(() => skipForPage(page.value, pageSize.value));

function revIdx($index: number) {
  return reverseSerialIndex(total.value, skip.value, $index);
}
const dlg = ref(false);
const mode = ref<"add" | "edit">("add");
const editingId = ref<string | null>(null);
const form = reactive({
  name: "",
  code: "",
  description: "",
  modules: [] as string[],
});

const dlgTitle = computed(() => (mode.value === "add" ? "添加角色" : "修改角色"));

const moduleLabelMap = Object.fromEntries(ROLE_MODULE_OPTIONS.map((o) => [o.value, o.label]));

function moduleLabels(row: Record<string, unknown>): string[] {
  const raw = row.modules;
  if (!Array.isArray(raw)) return [];
  return raw.map((x) => moduleLabelMap[String(x)] || String(x)).filter(Boolean);
}

async function load() {
  const { data } = await http.get("/api/roles", {
    params: { skip: skip.value, limit: pageSize.value },
  });
  const list = (data.items || []) as Record<string, unknown>[];
  const t = Number((data as { total?: number }).total);
  if (list.length === 0 && t > 0 && page.value > 1) {
    page.value = 1;
    return load();
  }
  items.value = list;
  total.value = Number.isFinite(t) ? t : 0;
}

function openAdd() {
  mode.value = "add";
  editingId.value = null;
  resetForm();
  dlg.value = true;
}

function openEdit(row: Record<string, unknown>) {
  mode.value = "edit";
  editingId.value = String(row._id);
  form.name = String(row.name);
  form.code = String(row.code);
  form.description = String(row.description || "");
  const m = row.modules;
  form.modules = Array.isArray(m) ? m.map(String) : [];
  dlg.value = true;
}

function resetForm() {
  form.name = "";
  form.code = "";
  form.description = "";
  form.modules = [];
}

async function save() {
  if (!form.modules.length) {
    ElMessage.warning("请至少勾选一个系统模块权限");
    return;
  }
  if (mode.value === "add") {
    await http.post("/api/roles", {
      name: form.name,
      code: form.code,
      description: form.description,
      modules: form.modules,
    });
  } else if (editingId.value) {
    await http.put(`/api/roles/${editingId.value}`, {
      name: form.name,
      description: form.description,
      modules: form.modules,
    });
  }
  dlg.value = false;
  ElMessage.success("已保存");
  await load();
}

async function remove(row: Record<string, unknown>) {
  await ElMessageBox.confirm("确定删除该角色？", "删除", { type: "warning" });
  await http.delete(`/api/roles/${row._id}`);
  ElMessage.success("已删除");
  await load();
}

watch(pageSize, () => {
  page.value = 1;
});
watch(
  [page, pageSize],
  () => {
    void load();
  },
  { immediate: true }
);
</script>

<style scoped>
.row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.tag {
  margin-right: 6px;
  margin-bottom: 4px;
}
.muted {
  color: var(--app-text-muted);
  font-size: 13px;
}
.hint {
  margin: 8px 0 0;
  font-size: 12px;
  color: var(--app-text-hint);
  line-height: 1.5;
}
</style>
