// frontend/src/views/UsersView.vue
<template>
  <el-card>
    <template #header>
      <div class="row">
        <span>账号管理</span>
        <el-button type="primary" @click="openAdd">添加用户</el-button>
      </div>
    </template>
    <el-table :data="items" border stripe style="width: 100%" row-key="_id">
      <el-table-column label="序号" width="72" align="center">
        <template #default="{ $index }">{{ revIdx($index) }}</template>
      </el-table-column>
      <el-table-column prop="_id" label="用户ID" width="200" />
      <el-table-column prop="username" label="用户名" />
      <el-table-column label="角色">
        <template #default="{ row }">{{ roleDisplayName(String(row.role)) }}</template>
      </el-table-column>
      <el-table-column prop="phone" label="手机号" />
      <el-table-column label="创建时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.created_at) }}</template>
      </el-table-column>
      <el-table-column label="更新时间" width="180">
        <template #default="{ row }">{{ formatDateTime(row.updated_at) }}</template>
      </el-table-column>
      <el-table-column label="操作" width="160" fixed="right">
        <template #default="{ row }">
          <el-button link type="primary" @click="openEdit(row)">修改</el-button>
          <el-button link type="danger" @click="remove(row)">删除</el-button>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination
      v-model:current-page="page"
      v-model:page-size="pageSize"
      :total="total"
      :page-sizes="[10, 20, 50, 100]"
      layout="total, sizes, prev, pager, next, jumper"
      class="table-pager"
    />

    <el-dialog v-model="dlg" :title="dlgTitle" width="520px" @closed="resetForm">
      <el-form :model="form" label-width="100px">
        <el-form-item label="用户名" required>
          <el-input v-model="form.username" :disabled="mode === 'edit'" />
        </el-form-item>
        <el-form-item label="密码" :required="mode === 'add'">
          <el-input v-model="form.password" type="password" show-password />
        </el-form-item>
        <el-form-item label="角色" required>
          <el-select v-model="form.role" style="width: 100%" filterable placeholder="选择角色">
            <el-option v-for="o in roleOptions" :key="o.value" :label="o.label" :value="o.value" />
          </el-select>
        </el-form-item>
        <el-form-item label="手机号">
          <el-input v-model="form.phone" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dlg = false">取消</el-button>
        <el-button type="primary" @click="save">保存</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup lang="ts">
import { reactive, ref, computed, watch } from "vue";
import http from "@/api/http";
import { ElMessage, ElMessageBox } from "element-plus";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

const items = ref<Record<string, unknown>[]>([]);
const total = ref(0);
const page = ref(1);
const pageSize = ref(DEFAULT_PAGE_SIZE);
const skip = computed(() => skipForPage(page.value, pageSize.value));

function revIdx($index: number) {
  return reverseSerialIndex(total.value, skip.value, $index);
}
const roleOptions = ref<{ label: string; value: string }[]>([]);

function roleDisplayName(code: string) {
  return roleOptions.value.find((o) => o.value === code)?.label ?? code;
}
const dlg = ref(false);
const mode = ref<"add" | "edit">("add");
const editingId = ref<string | null>(null);
const form = reactive({
  username: "",
  password: "",
  role: "evaluator",
  phone: "",
});

const dlgTitle = computed(() => (mode.value === "add" ? "添加用户" : "修改用户"));

async function load() {
  await loadRoleOptions();
  const { data } = await http.get("/api/users", {
    params: { skip: skip.value, limit: pageSize.value },
  });
  const list = (data.items || []) as Record<string, unknown>[];
  const t = Number((data as { total?: number }).total);
  if (list.length === 0 && t > 0 && page.value > 1) {
    page.value = 1;
    return load();
  }
  items.value = list;
  total.value = Number.isFinite(t) ? t : 0;
}

async function loadRoleOptions() {
  const { data } = await http.get("/api/roles", { params: { skip: 0, limit: 200 } });
  roleOptions.value = (data.items as Record<string, unknown>[]).map((r) => ({
    value: String(r.code),
    label: String(r.name),
  }));
}

function openAdd() {
  mode.value = "add";
  editingId.value = null;
  resetForm();
  dlg.value = true;
}

function openEdit(row: Record<string, unknown>) {
  mode.value = "edit";
  editingId.value = String(row._id);
  form.username = String(row.username);
  form.password = "";
  form.role = String(row.role);
  form.phone = String(row.phone || "");
  dlg.value = true;
}

function resetForm() {
  form.username = "";
  form.password = "";
  form.role = "evaluator";
  form.phone = "";
}

async function save() {
  if (mode.value === "add") {
    await http.post("/api/users", {
      username: form.username,
      password: form.password,
      role: form.role,
      phone: form.phone,
    });
  } else if (editingId.value) {
    const body: Record<string, string> = {
      username: form.username,
      role: form.role,
      phone: form.phone,
    };
    if (form.password) body.password = form.password;
    await http.put(`/api/users/${editingId.value}`, body);
  }
  dlg.value = false;
  ElMessage.success("已保存");
  await load();
}

async function remove(row: Record<string, unknown>) {
  await ElMessageBox.confirm("确定删除该用户？", "删除", { type: "warning" });
  await http.delete(`/api/users/${row._id}`);
  ElMessage.success("已删除");
  await load();
}

watch(pageSize, () => {
  page.value = 1;
});
watch(
  [page, pageSize],
  () => {
    void load();
  },
  { immediate: true }
);
</script>

<style scoped>
.row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// frontend/src/views/UsersView.tsx
import { useEffect, useMemo, useState } from "react";
import { Table, Button, Modal, Form, Input, Select, message, Card } from "antd";
import type { TablePaginationConfig } from "antd";
import http from "@/api/http";
import { formatDateTime } from "@/utils/datetime";
import { DEFAULT_PAGE_SIZE, reverseSerialIndex, skipForPage } from "@/utils/pagination";

type Row = Record<string, unknown>;

export default function UsersView() {
  const [items, setItems] = useState<Row[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(DEFAULT_PAGE_SIZE);
  const [dlg, setDlg] = useState(false);
  const [mode, setMode] = useState<"add" | "edit">("add");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [roleOptions, setRoleOptions] = useState<{ label: string; value: string }[]>([]);
  const [form] = Form.useForm();
  const skip = useMemo(() => skipForPage(page, pageSize), [page, pageSize]);

  async function load() {
    await loadRoleOptions();
    const { data } = await http.get("/api/users", { params: { skip, limit: pageSize } });
    const list = (data.items || []) as Row[];
    const t = Number(data.total);
    if (list.length === 0 && t > 0 && page > 1) { setPage(1); return; }
    setItems(list);
    setTotal(Number.isFinite(t) ? t : 0);
  }

  async function loadRoleOptions() {
    const { data } = await http.get("/api/roles", { params: { skip: 0, limit: 200 } });
    setRoleOptions((data.items as Row[]).map((r) => ({ value: String(r.code), label: String(r.name) })));
  }

  useEffect(() => { void load(); }, [page, pageSize]);

  function openAdd() {
    setMode("add"); setEditingId(null);
    form.resetFields(); form.setFieldsValue({ role: "evaluator" });
    setDlg(true);
  }

  function openEdit(row: Row) {
    setMode("edit"); setEditingId(String(row._id));
    form.setFieldsValue({ username: row.username, password: "", role: row.role, phone: row.phone || "" });
    setDlg(true);
  }

  async function save() {
    const vals = await form.validateFields();
    if (mode === "add") {
      await http.post("/api/users", vals);
    } else if (editingId) {
      const body: Record<string, string> = { username: vals.username, role: vals.role, phone: vals.phone || "" };
      if (vals.password) body.password = vals.password;
      await http.put(`/api/users/${editingId}`, body);
    }
    setDlg(false); message.success("已保存"); await load();
  }

  async function remove(row: Row) {
    Modal.confirm({ title: "确定删除该用户？", okType: "danger", onOk: async () => {
      await http.delete(`/api/users/${row._id}`);
      message.success("已删除"); await load();
    }});
  }

  const pagination: TablePaginationConfig = {
    current: page, pageSize, total,
    pageSizeOptions: [10, 20, 50, 100], showSizeChanger: true, showTotal: (t) => `共 ${t} 条`,
    onChange: (p, ps) => { if (ps !== pageSize) { setPageSize(ps); setPage(1); } else setPage(p); },
  };

  const columns = [
    { title: "序号", width: 72, align: "center" as const, render: (_: unknown, __: unknown, i: number) => reverseSerialIndex(total, skip, i) },
    { title: "用户ID", dataIndex: "_id", width: 200 },
    { title: "用户名", dataIndex: "username" },
    { title: "角色", dataIndex: "role", render: (v: string) => roleOptions.find((o) => o.value === v)?.label ?? v },
    { title: "手机号", dataIndex: "phone" },
    { title: "创建时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.created_at) },
    { title: "更新时间", width: 180, render: (_: unknown, row: Row) => formatDateTime(row.updated_at) },
    { title: "操作", width: 160, fixed: "right" as const, render: (_: unknown, row: Row) => (<><Button type="link" onClick={() => openEdit(row)}>修改</Button><Button type="link" danger onClick={() => remove(row)}>删除</Button></>) },
  ];

  return (
    <Card title={<div style={{ display: "flex", justifyContent: "space-between" }}><span>账号管理</span><Button type="primary" onClick={openAdd}>添加用户</Button></div>}>
      <Table rowKey="_id" dataSource={items} columns={columns} pagination={pagination} bordered size="small" scroll={{ x: "max-content" }} />
      <Modal title={mode === "add" ? "添加用户" : "修改用户"} open={dlg} onOk={save} onCancel={() => setDlg(false)} afterClose={() => form.resetFields()}>
        <Form form={form} labelCol={{ span: 6 }}>
          <Form.Item label="用户名" name="username" rules={[{ required: true }]}>
            <Input disabled={mode === "edit"} />
          </Form.Item>
          <Form.Item label="密码" name="password" rules={mode === "add" ? [{ required: true }] : []}>
            <Input.Password />
          </Form.Item>
          <Form.Item label="角色" name="role" rules={[{ required: true }]}>
            <Select options={roleOptions} />
          </Form.Item>
          <Form.Item label="手机号" name="phone"><Input /></Form.Item>
        </Form>
      </Modal>
    </Card>
  );
}
